//
//  RegisterModels.swift
//  OSC
//
//  Created by Dyan Galih on 07/05/19.
//  Copyright (c) 2019 Dyan Galih. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Register
{
    // MARK: Use cases
    
    enum NewUser
    {
        struct Request
        {
            var name: String
            var email: String
            var password: String
            var password_confirmation: String
            init(name: String, email: String, password: String, password_confirmation: String) {
                self.name = name
                self.email = email
                self.password = password
                self.password_confirmation = password_confirmation
            }
        }
        struct Response:Decodable
        {
            var code: Int32
            var error: Bool
            var message: String
        }
        struct ViewModel
        {
        }
    }
}
