//
//  RegisterRouter.swift
//  OSC
//
//  Created by Dyan Galih on 07/05/19.
//  Copyright (c) 2019 Dyan Galih. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol RegisterRoutingLogic {
    func routeToLogin(segue: UIStoryboardSegue?)
}

protocol RegisterDataPassing {
    var dataStore: RegisterDataStore? { get }
}

class RegisterRouter: NSObject, RegisterRoutingLogic, RegisterDataPassing {
    weak var viewController: RegisterViewController?
    var dataStore: RegisterDataStore?

    // MARK: Routing

    func routeToLogin(segue: UIStoryboardSegue?) {
//        if let segue = segue {
//            _ = segue.destination as! LoginViewController
//        } else {
//            let storyboard = UIStoryboard(name: "Main", bundle: nil)
//            let destinationVC = storyboard.instantiateViewController(withIdentifier: "LoginViewController") as! LoginViewController
//            navigateToLogin(source: viewController!, destination: destinationVC)
//        }
        
        viewController?.present(LoginViewController(), animated: true, completion: nil)
    }

    // MARK: Navigation

    func navigateToLogin(source: RegisterViewController, destination: LoginViewController) {
        source.show(destination, sender: nil)
        source.dismiss(animated: false, completion: nil)
    }

    // MARK: Passing data

    // func passDataToSomewhere(source: RegisterDataStore, destination: inout SomewhereDataStore)
    // {
    //  destination.name = source.name
    // }
}
