//
//  RegisterWorker.swift
//  OSC
//
//  Created by Dyan Galih on 07/05/19.
//  Copyright (c) 2019 Dyan Galih. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Alamofire
import UIKit

class RegisterWorker {
    func doRegister(request: Register.NewUser.Request, completion: @escaping (Register.NewUser.Response?, Error?) -> Void) {
        let parameters = [
            "firstname": request.firstname,
            "lastname": request.lastname,
            "email": request.email,
            "password": request.password
        ]

        Alamofire.request(Config().endpoint + "/registration", method: .post, parameters: parameters as Parameters, encoding: JSONEncoding.default).debugLog().responseJSON { response in
            do {
                let registerStruct = try JSONDecoder().decode(Register.NewUser.Response.self, from: response.data!)
                if registerStruct.code == 201 {
                    completion(registerStruct, nil)
                } else {
                    completion(nil, nil)
                }
            } catch let err {
                completion(nil, err)
            }
        }
    }
}
