//
//  RegisterPresenter.swift
//  OSC
//
//  Created by Dyan Galih on 07/05/19.
//  Copyright (c) 2019 Dyan Galih. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RegisterPresentationLogic {
    func presentRegisterSuccess()
    func presentRegisterFailed(title: String, message: String)
}

class RegisterPresenter: RegisterPresentationLogic {
    weak var viewController: RegisterDisplayLogic?

    // MARK: Do something

    func presentRegisterSuccess() {
        viewController?.displaySuccessRegister()
    }

    func presentRegisterFailed(title: String, message: String) {
        viewController?.displayRegisterFailed(title: title, message: message)
    }
}
