//
//  CategoryWorker.swift
//  OSC
//
//  Created by Dyan Galih on 27/05/19.
//  Copyright (c) 2019 Dyan Galih. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Alamofire
import UIKit

class CategoryWorker: BaseWorker {
    func doGetCategoryList(completion: @escaping (Category.List.Response?, Error?) -> Void) {
        Alamofire.request(Config().endpoint + "/category", method: .get, headers: getHeader()).debugLog().responseJSON { response in
            do {
                let categoryStruct = try JSONDecoder().decode(Category.List.Response.self, from: response.data!)
                completion(categoryStruct, nil)
            } catch let err {
                completion(nil, err)
            }
        }
    }
}
