//
//  CategoryInteractor.swift
//  OSC
//
//  Created by Dyan Galih on 27/05/19.
//  Copyright (c) 2019 Dyan Galih. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CategoryBusinessLogic
{
    func doGetCategoryList(request: Category.List.Request)
}

protocol CategoryDataStore
{
    // var name: String { get set }
}

class CategoryInteractor: CategoryBusinessLogic, CategoryDataStore
{
    var presenter: CategoryPresentationLogic?
    var worker: CategoryWorker?
    // var name: String = ""

    // MARK: Do something

    func doGetCategoryList(request: Category.List.Request)
    {
        worker = CategoryWorker()
        worker?.doGetCategoryList(completion: { (data, _) -> Void in
            if data != nil
            {
                let response: Category.List.Response = data!
                self.presenter?.presentCategoryList(response: response)
            }
            else
            {
                self.presenter?.presentAlert(message: "Data Not Found")
            }
        })
    }
}
