//
//  CategoryPresenter.swift
//  OSC
//
//  Created by Dyan Galih on 27/05/19.
//  Copyright (c) 2019 Dyan Galih. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CategoryPresentationLogic {
    func presentCategoryList(response: Category.List.Response)
    func presentAlert(message: String)
}

class CategoryPresenter: CategoryPresentationLogic {
    weak var viewController: CategoryDisplayLogic?

    func presentCategoryList(response: Category.List.Response) {
        let viewModel = Category.List.ViewModel(data: response.data)
        viewController?.displayCategoryList(viewModel: viewModel)
    }

    func presentAlert(message: String) {
        viewController?.displayAlert(title: "Category List", message: message)
    }
}
