//
//  HomeInteractor.swift
//  OSC
//
//  Created by Dyan Galih on 13/05/19.
//  Copyright (c) 2019 Dyan Galih. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic
{
  func doGetHomeData(request: Home.Data.Request)
}

protocol HomeDataStore
{
  //var name: String { get set }
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore
{
  var presenter: HomePresentationLogic?
  var worker: HomeWorker?
  
  // MARK: Do something
  
  func doGetHomeData(request: Home.Data.Request)
  {
    worker = HomeWorker()
    worker?.doGetHomeData(completion: { (data, err) -> Void
        in
        if data != nil{
            let response:Home.Data.Response = data!
            self.presenter?.presentHomeData(response: response)
        }else{
            print("no data")
        }
    })
  }
}
