//
//  HomeModels.swift
//  OSC
//
//  Created by Dyan Galih on 13/05/19.
//  Copyright (c) 2019 Dyan Galih. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home {
    // MARK: Use cases

    enum List {
        struct Request {}

        struct Data: Decodable {
            var id: String
            var name: String
        }

        struct Response: Decodable {
            var code: Int32
            var message: String
            var data: [Data]
        }

        struct ViewModel {
            var data: [Data]
        }
    }
}
