//
//  HomeWorker.swift
//  OSC
//
//  Created by Dyan Galih on 13/05/19.
//  Copyright (c) 2019 Dyan Galih. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

class HomeWorker
{
    func doGetHomeData(completion:@escaping (Home.Data.Response?, Error?) -> Void)
    {
        Alamofire.request(Config().endpoint + "/homepage", method: .get).debugLog().responseJSON{
            response in
            do{
                let homeStruct = try JSONDecoder().decode(Home.Data.Response.self, from: response.data!)
                completion(homeStruct, nil)
            }catch let err{
                completion(nil, err)
            }
        }
    }
}
