//
//  ProductDetailModels.swift
//  OSC
//
//  Created by Dyan Galih on 08/07/19.
//  Copyright (c) 2019 Dyan Galih. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ProductDetail
{
    // MARK: Use cases

    enum Item
    {
        struct Request
        {}

        struct Response
        {}

        struct ViewModel
        {
            var id: String
            var name: String
            var price: Int32
            var promoted_product: Bool
            var promote_title: String
            var thumbnail: String
        }
    }

    enum Like
    {
        struct Request
        {
            var id: String
        }

        struct Response: Decodable
        {
            var code: Int32
            var message: String
            var data: String?
        }
    }
}
