//
//  ProductDetailPresenter.swift
//  OSC
//
//  Created by Dyan Galih on 08/07/19.
//  Copyright (c) 2019 Dyan Galih. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductDetailPresentationLogic
{
    func presentProductDetail(response: ProductDetail.DetailItem.Data)
    func presentSuccessLike(message: String)
}

class ProductDetailPresenter: ProductDetailPresentationLogic
{
    weak var viewController: ProductDetailDisplayLogic?

    // MARK: Do something

    func presentSuccessLike(message: String)
    {
        viewController?.showSuccessLike(message: message)
    }

    func presentProductDetail(response: ProductDetail.DetailItem.Data)
    {
        let viewModel = ProductDetail.DetailItem.ViewModel(id: response.id, name: response.name, description: response.description, thumbnail: response.thumbnail, file: response.file, price: response.price, preview_file_type: response.preview_file_type, download_remaining: response.download_remaining, view_count: response.view_count, like_count: response.like_count)
        viewController?.displayProductDetail(viewModel: viewModel)
    }
}
