//
//  ProductDetailPresenter.swift
//  OSC
//
//  Created by Dyan Galih on 08/07/19.
//  Copyright (c) 2019 Dyan Galih. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductDetailPresentationLogic
{
    func presentProductDetail(response: Product.List.Item)
}

class ProductDetailPresenter: ProductDetailPresentationLogic
{
    weak var viewController: ProductDetailDisplayLogic?

    // MARK: Do something

    func presentProductDetail(response: Product.List.Item)
    {
        let viewModel = ProductDetail.Item.ViewModel(id: response.id, name: response.name, price: response.price, promoted_product: response.promoted_product, promote_title: response.promote_title, thumbnail: response.thumbnail)
        viewController?.displayProductDetail(viewModel: viewModel)
    }
}
