//
//  ProductRouter.swift
//  OSC
//
//  Created by Dyan Galih on 25/06/19.
//  Copyright (c) 2019 Dyan Galih. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ProductRoutingLogic
{
    func routeToProductDetail(segue: UIStoryboardSegue?)
}

protocol ProductDataPassing
{
    var dataStore: ProductDataStore? { get }
}

class ProductRouter: NSObject, ProductRoutingLogic, ProductDataPassing
{
    weak var viewController: ProductViewController?
    var dataStore: ProductDataStore?
    
    // MARK: Routing
    
    func routeToProductDetail(segue: UIStoryboardSegue?)
    {
        if let segue = segue
        {
            let destinationVC = segue.destination as! ProductDetailViewController
            _ = destinationVC.router!.dataStore!
        }
        else
        {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "ProductDetailViewController") as! ProductDetailViewController
            
            var destinationDS = destinationVC.router!.dataStore!
            passDataToProductDetail(source: dataStore!, destination: &destinationDS)
            navigateToProductDetail(source: viewController!, destination: destinationVC)
        }
    }
    
    func navigateToProductDetail(source: ProductViewController, destination: ProductDetailViewController)
    {
        source.navigationController?.pushViewController(destination, animated: true)
    }
    
    // MARK: Passing data
    
    func passDataToProductDetail(source: ProductDataStore, destination: inout ProductDetailDataStore)
    {
        let selectedRow = viewController?.tableProductView.indexPathForSelectedRow?.row
        destination.productItem = source.productItem?[selectedRow!]
    }
}
