//
//  ProductPresenter.swift
//  OSC
//
//  Created by Dyan Galih on 25/06/19.
//  Copyright (c) 2019 Dyan Galih. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductPresentationLogic
{
    func presentProductList(response: Product.List.Response)
    func presentAlert(message: String)
}

class ProductPresenter: ProductPresentationLogic
{
    weak var viewController: ProductDisplayLogic?

    // MARK: Do something

    func presentProductList(response: Product.List.Response)
    {
        let viewModel = Product.List.ViewModel(data: response.data)
        
        viewController?.displayProductList(viewModel: viewModel)
    }

    func presentAlert(message: String)
    {
        viewController?.displayNotFound(title: "Product List", message: message)
    }
}
