//
//  ProductWorker.swift
//  OSC
//
//  Created by Dyan Galih on 25/06/19.
//  Copyright (c) 2019 Dyan Galih. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Alamofire
import UIKit

class ProductWorker: BaseWorker {
    func doGetProductList(completion: @escaping (Product.List.Response?, Error?) -> Void) {
        Alamofire.request(Config().endpoint + "/guest/product", method: .get, headers: getHeader()).debugLog().responseJSON {
            response in
            do {
                let productStruct = try JSONDecoder().decode(Product.List.Response.self, from: response.data!)
                completion(productStruct, nil)
            } catch let err {
                print(err)
                completion(nil, err)
            }
        }
    }
}
