//
//  ProductModels.swift
//  OSC
//
//  Created by Dyan Galih on 25/06/19.
//  Copyright (c) 2019 Dyan Galih. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Product {
    // MARK: Use cases

    enum List {
        struct Request
        {}

        struct Item: Decodable {
            var id: String
            var name: String
            var price: Int32
            var promoted_product: Bool
            var promote_title: String
            var thumbnail: String
            var preview: Preview

            struct Preview: Decodable {
                var String: String
                var Valid: Bool
            }
        }
        
        struct Response: Decodable {
            var code: Int32
            var message: String
            var data: [Item]
            var length: Int32
        }

        struct ViewModel {
            var data: [Item]
        }
    }
}
