//
//  ProductModels.swift
//  OSC
//
//  Created by Dyan Galih on 25/06/19.
//  Copyright (c) 2019 Dyan Galih. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Product {
    // MARK: Use cases

    enum List {
        struct TimeFormat: Decodable {
            var Time: String
            var Valid: Bool
        }

        struct Request
        {}
        struct Item: Decodable {
            var id: String
            var category_id: Int32
            var subcategory_id: Int32
            var category: String
            var subcategory: String
            var name: String
            var description: String
            var thumbnail: String
            var file: String
            var created_at: TimeFormat
            var updated_at: TimeFormat
        }

        struct Data: Decodable {
            var count: Int32
            var list: [Item]
        }

        struct Response: Decodable {
            var code: Int32
            var message: String
            var data: Data
        }

        struct ViewModel
        {
            var data: [Item]
        }
    }
}
