//
//  ProductInteractor.swift
//  OSC
//
//  Created by Dyan Galih on 25/06/19.
//  Copyright (c) 2019 Dyan Galih. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductBusinessLogic
{
    func doGetProductList(request: Product.List.Request)
}

protocol ProductDataStore
{
    var productItem: [Product.List.Item]? { get set }
}

class ProductInteractor: ProductBusinessLogic, ProductDataStore
{
    var productItem: [Product.List.Item]?
    var presenter: ProductPresentationLogic?
    var worker: ProductWorker?

    // MARK: Do something

    func doGetProductList(request: Product.List.Request)
    {
        worker = ProductWorker()
        worker?.doGetProductList(completion: { (data, _) -> Void in
            if data != nil
            {
                self.productItem = data?.data
                let response: Product.List.Response = data!
                self.presenter?.presentProductList(response: response)
            }
            else
            {
                self.presenter?.presentAlert(message: "Data Not Found")
            }
        })
    }
}
