//
//  ForgotPasswordPresenter.swift
//  OSC
//
//  Created by Dyan Galih on 14/05/19.
//  Copyright (c) 2019 Dyan Galih. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ForgotPasswordPresentationLogic
{
    func presentSucessForgotPassword()
    func presentFailedReqForgotPassword()
}

class ForgotPasswordPresenter: ForgotPasswordPresentationLogic
{
    func presentFailedReqForgotPassword() {
        viewController?.displayMessage(title: "Request Failed", message: "Request Reset Password Failed, please contact adminstrator")
    }
    
    weak var viewController: ForgotPasswordDisplayLogic?
    
    // MARK: Do something
    
    func presentSucessForgotPassword()
    {
        let viewModel = ForgotPassword.Forgot.ViewModel()
        viewController?.displayMessage(title: "Request Success", message: "Request Reset Password Success, Please Check Your Email")
    }
}
