//
//  ForgotPasswordWorker.swift
//  OSC
//
//  Created by Dyan Galih on 14/05/19.
//  Copyright (c) 2019 Dyan Galih. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

class ForgotPasswordWorker
{
    func doForgotPassword(request: ForgotPassword.Forgot.Request, completion: @escaping(ForgotPassword.Forgot.Response?, Error?) -> Void)
    {
        let parameters = [
            "email": request.email
        ]
        
        Alamofire.request(Config().endpoint + "api/forgot_password", method: .post, parameters: parameters, encoding: URLEncoding.default).debugLog()
            .responseJSON{
                response in
                do {
                    let forgotPasswordStruct = try JSONDecoder().decode(ForgotPassword.Forgot.Response.self, from: response.data!)
                    completion(forgotPasswordStruct, nil)
                }catch let err{
                    completion(nil, err)
                }
        }
    }
}
