//
//  LoginViewController.swift
//  OSC
//
//  Created by Dyan Galih on 07/05/19.
//  Copyright (c) 2019 Dyan Galih. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginDisplayLogic: class {
    func showLoginAlert(tilte: String, message: String)
    func showSuccessLogin()
}

class LoginViewController: UIViewController, LoginDisplayLogic {
    var interactor: LoginBusinessLogic?
    var router: (NSObjectProtocol & LoginRoutingLogic & LoginDataPassing)?

    @IBOutlet var emailTxt: UITextField!
    @IBOutlet var pinTxt: UITextField!
    @IBOutlet var loginButton: UIButtonActivity!

    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: Setup

    private func setup() {
        let viewController = self
        let interactor = LoginInteractor()
        let presenter = LoginPresenter()
        let router = LoginRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    func cleanupForm(){
        emailTxt.text = ""
        pinTxt.text = ""
    }
    
    func showSuccessLogin() {
        showAlert(title: "Login Success", message: "Welcome Back", handler: routeToHome(_:))
        loginButton.stopAnimating()
    }

    func routeToHome(_: UIAlertAction) {
        router?.routeToHome(segue: nil)
        cleanupForm()
    }

    func showLoginAlert(tilte: String, message: String) {
        loginButton.stopAnimating()
        showAlert(title: title ?? "Login Failed", message: message, handler: nil)
    }

    @IBAction func loginBtnAction(_ sender: UIButton) {
        loginButton.startAnimating()
        let email: String = emailTxt.text!
        let pin: String = pinTxt.text!

        let request = Login.User.Request(email: email, password: pin)
        interactor?.doLogin(request: request)
    }

    @IBAction func btnRegister(_ sender: UIButton) {
        router?.routeToRegister(segue: nil)
    }

    @IBAction func btnForgotPassword(_ sender: UIButton) {
        router?.routeToForgotPassword(segue: nil)
    }
}
