//
//  LoginModels.swift
//  OSC
//
//  Created by Dyan Galih on 07/05/19.
//  Copyright (c) 2019 Dyan Galih. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login
{
    // MARK: Use cases
    
    enum User
    {
        struct Request
        {
            var email: String
            var password: String
            init(email: String, password: String) {
                self.email = email
                self.password = password
            }
        }
        struct Response
        {
        }
        
        struct LoginResponse: Decodable{
            var tokenType: String
            var expiresIn: Int32
            var accessToken: String
            var refreshToken: String
        }
        
        struct ViewModel
        {
        }
    }
}
