//
//  LoginInteractor.swift
//  OSC
//
//  Created by Dyan Galih on 07/05/19.
//  Copyright (c) 2019 Dyan Galih. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Alamofire
import UIKit

protocol LoginBusinessLogic {
    func doLogin(request: Login.User.Request)
}

protocol LoginDataStore {
    var name: String { get set }
}

class LoginInteractor: LoginBusinessLogic, LoginDataStore {
    var presenter: LoginPresentationLogic?
    var worker: LoginWorker?
    var name: String = ""

    // MARK: Do something

    func doLogin(request: Login.User.Request) {
        var message: String = ""
        var error: Bool = false
        if request.email.isEmpty {
            error = true
            message = "Please input your email"
        } else if request.password.isEmpty {
            error = true
            message = "Please input your password"
        }

        if error {
            presenter?.presentFailedLogin(title: "Login Failed", message: message)
        } else {
            worker = LoginWorker()
            worker?.doLogin(request: request, completion: { data, _ in
                if data != nil {
                    self.worker?.doStoreAuth(response: data!, completion: { bool in
                        if bool! {
                            self.presenter?.presentSuccessLogin()
                        } else {
                            self.presenter?.presentFailedLogin(title: "Login Failed", message: "Contact your administrator")
                        }
                    })

                } else {
                    self.presenter?.presentFailedLogin(title: "Login Failed", message: "Please check your email or password")
                }
            })
        }
    }
}
