//
//  LoginWorker.swift
//  OSC
//
//  Created by Dyan Galih on 07/05/19.
//  Copyright (c) 2019 Dyan Galih. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

class LoginWorker
{
    func doLogin(request: Login.User.Request, completion:@escaping (Login.User.LoginResponse?, Error?) -> Void)
    {
        let parameters = [
            "username": request.email,
            "password": request.password
        ]
        
        Alamofire.request(Config().endpoint + "auth/token", method: .post, parameters: parameters, encoding: URLEncoding.default).responseJSON{ response in
            do{
                let loginStruct = try JSONDecoder().decode(Login.User.LoginResponse.self, from: response.data!)
                completion(loginStruct, nil);
            }catch let err{
                completion(nil, err)
            }
        }
    }
}
