//
//  LoginModels.swift
//  OSC
//
//  Created by Dyan Galih on 07/05/19.
//  Copyright (c) 2019 Dyan Galih. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login
{
    // MARK: Use cases
    
    enum User
    {
        struct Request
        {
            var email: String
            var password: String
            init(email: String, password: String) {
                self.email = email
                self.password = password
            }
        }
        struct Response
        {
        }
        
        struct LoginResponse: Decodable{
            var code: Int32
            var message: String
            
            struct Data:Decodable{
                struct User: Decodable {
                    var id: Int32
                    var email: String
                    var password: String
                    var firstname: String
                    var lastname: String
                    struct CreatedAt: Decodable{
                        var Time: String
                        var Valid: Bool
                    }
                    var created_at:CreatedAt
                    
                    struct UpdatedAt:Decodable {
                        var Time: String
                        var Valid: Bool
                    }
                    var updated_at: UpdatedAt
                }
                var user: User
                var token: String
            }
            var data: Data
        }
        
        
        
        struct ViewModel
        {
        }
    }
}
